name: "Refresh jdk22 from Upstream"
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
    refresh-jdk22:
        runs-on: ubuntu-latest
        name: "Update Corretto-22"
        if: github.repository_owner == 'corretto'
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: "Fetch Corretto-22 upstream"
              uses: ./.github/actions/fetch-repo
              with:
                upstream: 'https://github.com/openjdk/jdk22.git'
                local-branch: 'upstream-jdk22'
            - name: "Merge Corretto-22"
              uses: ./.github/actions/merge-repo
              with:
                upstream: 'upstream-jdk22'
                merge-branch: 'develop'
            - name: "Update Corretto version"
              uses: ./.github/actions/update-version
              with:
                upstream: 'upstream-jdk22'
                version-branch: 'develop'
            - name: "Merge Corretto-22 develop to nightly"
              uses: ./.github/actions/merge-repo
              with:
                upstream: 'develop'
                merge-branch: 'nightly'
